global:
  resolve_timeout: 5m

route:
  receiver: slack
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 30m

receivers:
  - name: slack
    slack_configs:
      - api_url_file: /etc/alertmanager/secret/slack_webhook_url
        channel: '#daegis-alerts'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }} ({{ .Status }})'
        text: >-
          {{ range .Alerts -}}
          *{{ .Labels.severity | toUpper }}* {{ .Annotations.summary }}
          {{ "\n" -}}
          {{ end }}
