global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/*.yml
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'metrics'
    static_configs:
      - targets: ['metrics:8000']

  - job_name: 'latency-prober'
    static_configs:
      - targets: ['latency-prober:9108']
