global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['am-daegis:9093']

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-daegis:9100']
