services:
  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.retention.time=15d"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /tmp/ward-out/rules:/etc/prometheus/alerts.d:ro
      - /tmp/ward-out/file_sd:/etc/blackbox/ward-file-sd:ro
    ports: ["9091:9090"]

  nodeexporter:
    image: prom/node-exporter:latest
    pid: host
    network_mode: host
    command: ["--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|run)($|/)"]

  grafana:
    image: grafana/grafana:latest
    ports: ["3001:3000"]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning

  blackbox:
    image: prom/blackbox-exporter:latest
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml:ro
      # （blackbox側への file_sd マウントは不要だが、置いても無害）
      - /tmp/ward-out/file_sd:/etc/blackbox/ward-file-sd:ro
    ports: ["9115:9115"]
