#!/usr/bin/env bash
set -euo pipefail
src="docs/copilot/INSTRUCTIONS.md"
dst="docs/copilot/README.md"

if [ ! -f "$src" ]; then
  echo "ERROR: $src not found" >&2
  exit 1
fi

mkdir -p "$(dirname "$dst")"
{
  echo "# Copilot · Working Index"
  echo ""
  echo "_This file is auto-generated from **INSTRUCTIONS.md**. Do not edit this file directly._"
  echo ""
  echo "<!-- BEGIN AUTO-INCLUDE -->"
  cat "$src"
  echo "<!-- END AUTO-INCLUDE -->"
} > "$dst"

echo "Wrote $dst from $src"
