alias loglast='$HOME/daegis/tools/loglast.sh'
alias rtsmoke='$HOME/daegis/tools/rt-smoke.sh'
alias health='$HOME/daegis/tools/health.sh'
alias rt-health='$HOME/daegis/tools/rt-health.sh'
alias mqtt-smoke='$HOME/daegis/tools/mqtt-smoke.sh'
alias rt-smoke='$HOME/daegis/tools/rt-smoke.sh'
