name: nightly-brief
on:
  schedule: [{cron: '7 0 * * *'}]   # UTC 00:07
  workflow_dispatch:

jobs:
  brief:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout brief-rollup
        uses: actions/checkout@v4
        with:
          ref: brief-rollup

      - name: Make brief
        run: |
          mkdir -p ops/ai
          chmod +x tools/make-brief.sh
          tools/make-brief.sh

      - name: Commit brief
        run: |
          git config user.name  'daegis-bot'
          git config user.email 'daegis-bot@users.noreply.github.com'
          git add ops/ai/brief.md
          git commit -m "ci: nightly brief update" || echo "no changes"
          git push
