name: secret-grep
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Fail if Slack webhook pattern is found
        run: |
          set -euo pipefail
          RANGE="${{ github.event_name == 'pull_request' && format('origin/{0}...HEAD', github.base_ref) || 'HEAD~20..HEAD' }}"
          git rev-list --no-merges $RANGE | xargs -r -n1 git show --pretty="" --name-only \
          | xargs -r grep -nE 'https://hooks\.slack\.com/' -- \
              . \
              ':!venv/**' ':!**/venv/**' ':!**/site-packages/**' \
              ':!node_modules/**' ':!**/*.log' ':!**/*.bak*' ':!**/*.backup*' ':!**/*.env' \
              ':!ops/staging-snap/**' ':!ops/**/notifiers.bak/**' ':!ops/**/contact-points*.yaml' \
          && { echo "::error::Slack webhook-like string found"; exit 1; } || echo "OK"
