services:
  alertmanager:
    image: prom/alertmanager:v0.27.0
    command:
      - --config.file=/etc/am/alertmanager.yml
      - --web.listen-address=:9093
    volumes:
      - ../monitoring/alertmanager/alertmanager.yml:/etc/am/alertmanager.yml:ro
    env_file:
      - ~/.config/daegis/.env.local
    ports:
      - "9093:9093"
